development:
  DB_ADAPTER: mysql2
  DB_ENCODING: utf8
  DB_DATABASE: songuo_community
  DB_USERNAME: root
  DB_PASSWORD: LS1ster
  DB_HOST: localhost
  DB_PORT: 3306

  TRUSTED_IP: 10.1.1.0/24

test:
  DB_ADAPTER: mysql2
  DB_ENCODING: utf8
  DB_DATABASE: songuo_community_test
  DB_USERNAME: root
  DB_PASSWORD: LS1ster
  DB_HOST: localhost
  DB_PORT: 3306

production:
  DB_ADAPTER: mysql2
  DB_ENCODING: utf8
  DB_DATABASE: songuo_community_production
  DB_USERNAME: root
  DB_PASSWORD: LS1ster
  DB_HOST: localhost
  DB_PORT: 3306
